{% set version = "0.1.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-miniui
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/miniUI_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/miniUI/miniUI_{{ version }}.tar.gz
  sha256: 017a481f7584d385241720f568323b8636ddad385e7098ceff5c12ebf879c22f

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-htmltools >=0.3
    - r-shiny >=0.13
  run:
    - r-base
    - r-htmltools >=0.3
    - r-shiny >=0.13

test:
  commands:
    - $R -e "library('miniUI')"           # [not win]
    - "\"%R%\" -e \"library('miniUI')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=miniUI
  license: GPL-3.0-only
  summary: Provides UI widget and layout functions for writing Shiny apps that work well on small screens.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
